### ISSUE TITLE
Setup using latest version 1.0.1

### ISSUE THREAD

**Issue by raghav-gupta** [Azure/azure-notificationhubs-android#115]
I am implementing the latest version ending with v1.0.1 but what all steps to follow to listen to a notification. 
And for reference I tried with FCM Tutorial App given in repository ,it uses the older version 0.6

I am confused on the part :
1) Do we need Broadcast Receivers in Manifest File , which I think now usually don't work unless we register programtically.
2) FirebaseInstanceIdService which is also kind of deprecated.
3) Does the new version handles all this boiler plate code for us for setting up the FCM in our app and Azure classes utilizing the same by itself.

**Comment by marstr** [comment]
Thanks for reaching out. Before I get into it, can I ask if you're planning on using the older Registration flow seen in `com.microsoft.windowsazure.messaing`, or the newer Installation flow in `com.microsoft.windowsazure.messaging.notificationhubs`? The former is likely what you're reading form in the FCM Tutorial, but the latter should be much much simpler and bypass all of these questions by handling it all for you.

**Comment by mpodwysocki** [comment]
Closing as per stale issue.  If this remains an issue, please reopen
