### ISSUE TITLE
Listening to FCM notification when app is in killed state

### ISSUE THREAD

**Issue by hiteshGlobal** [Azure/azure-notificationhubs-android#116]
I am using latest version of NotificationHub(1.0.1). To receive to notifications when application is in killed state I need to start the azure SDK in a custom class that extends Application.class in android. I get exception in the logs when call the below method
`NotificationHub.start(this.getApplication(), BuildConfig.hubName, BuildConfig.hubListenConnectionString);`

Error message : Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.cegid.flow/com.microsoft.windowsazure.messaging.notificationhubs.FirebaseReceiver }: app is in background uid UidRecord{70e259d u0a846 RCVR idle change:uncached procs:1 seq(0,0,0)}

In Android Oreo and above devices we cannot start a service from background. If I catch this exception then I can receive the notification in the Notification listener. Is there any other approach to register for notification when app is killed.

If I do not call NotificationHub.start() method in the custom Application class then I get below exception.

Error message: java.lang.RuntimeException: Unable to create service com.microsoft.windowsazure.messaging.notificationhubs.FirebaseReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.microsoft.windowsazure.messaging.notificationhubs.PushChannelVisitor.getPushChannel()' on a null object reference.

 - OS: Android 9
 - IDE : Android Studio 4.0.1
 - 1.0.1

**Comment by marstr** [comment]
Thanks for this feedback. I believe the following two lines are probably the source of the problem: 

https://github.com/Azure/azure-notificationhubs-android/blob/5f8189f58e76191a9f0e20aa4bc57728e72d57eb/notification-hubs-sdk/src/main/java/com/microsoft/windowsazure/messaging/notificationhubs/NotificationHub.java#L118-L119

These were added to be certain that the FirebaseReceiver was started and listening. However, I believe this was a redundant step as Android should start this service lazily when a Notification is received regardless. For that reason, these two lines should probably be removed to fix your issue. I'll need to validate and test this assumption, but it should be pretty straight forward.

**Comment by marstr** [comment]
Also, I'd like to clarify: Where in the application lifecycle are you calling `NotificationHub.start()`? In the sample applications, you can see we always initialize in the launch Activity's `onCreate` using `this.getApplication()`:

https://github.com/Azure/azure-notificationhubs-android/blob/5f8189f58e76191a9f0e20aa4bc57728e72d57eb/notification-hubs-test-app-java/src/main/java/com/example/notification_hubs_test_app_java/MainActivity.java#L24

**Comment by hiteshGlobal** [comment]
> Also, I'd like to clarify: Where in the application lifecycle are you calling `NotificationHub.start()`? In the sample applications, you can see we always initialize in the launch Activity's `onCreate` using `this.getApplication()`:
> 
> https://github.com/Azure/azure-notificationhubs-android/blob/5f8189f58e76191a9f0e20aa4bc57728e72d57eb/notification-hubs-test-app-java/src/main/java/com/example/notification_hubs_test_app_java/MainActivity.java#L24

Thanks for quick reply @marstr . I will be calling this in app's MainActivity's onCreate method once this issue is fixed. But for now calling it in BaseApplication class so that app can receive notification in background and using try catch for exception. Let me know if I should use some other approach. 

Also how can we de-register a device for notification using SDK? As in the case of logout I don't want app to receive notification.

Thanks!

**Comment by marstr** [comment]
> Also how can we de-register a device for notification using SDK? As in the case of logout I don't want app to receive notification.

Unfortunately this isn't supported out of the box today! Though, your scenario makes sense to me. If we hear this feedback from enough people, we'd be happy to add it this functionality in. We'll just to have think through how to add it without causing breaking changes.

The work around in the meantime would be to create your own REST call to the Delete Installation endpoint. If you're okay using Volley, you should be able to copy a bunch of the code in [`InstallationPutRequest`](https://github.com/Azure/azure-notificationhubs-android/blob/5f8189f58e76191a9f0e20aa4bc57728e72d57eb/notification-hubs-sdk/src/main/java/com/microsoft/windowsazure/messaging/notificationhubs/InstallationPutRequest.java#L36) to make authentication work. I'll try to think through ways we can make this more convenient moving forward.

**Comment by marstr** [comment]
This fix will be included in the next patch release. Should be pushed within the next week or so.

**Comment by marstr** [comment]
The fix should be available for you now in version 1.1.0, @hiteshGlobal.

**Comment by acastr7** [comment]
@marstr After updating to this version on Xamarin.Android I noticed our push notifications no longer work.

Here is the error we are seeing. It only happens on first launch and then we never see the FirebaseReceiver start again:
```
[AndroidRuntime] java.lang.RuntimeException: Unable to create service com.microsoft.windowsazure.messaging.notificationhubs.FirebaseReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.microsoft.windowsazure.messaging.notificationhubs.PushChannelVisitor.getPushChannel()' on a null object reference
[AndroidRuntime] 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3965)
[AndroidRuntime] 	at android.app.ActivityThread.access$1500(ActivityThread.java:219)
[AndroidRuntime] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:107)
[AndroidRuntime] 	at a08-19 17:28:05.991 E/AndroidRuntime( 9209): 	at android.os.Looper.loop(Looper.java:214)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:7356)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
[AndroidRuntime] Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.microsoft.windowsazure.messaging.notificationhubs.PushChannelVisitor.getPushChannel()' on a null object reference
[AndroidRuntime] 	at com.microsoft.windowsazure.messaging.notificationhubs.NotificationHub.getP08-19 17:28:05.991 E/AndroidRuntime( 9209): 	at com.microsoft.windowsazure.messaging.notificationhubs.NotificationHub.getInstancePushChannel(NotificationHub.java:257)
[AndroidRuntime] 	at com.microsoft.windowsazure.messaging.notificationhubs.FirebaseReceiver.onCreate(FirebaseReceiver.java:50)
[AndroidRuntime] 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3953)
[AndroidRuntime] 	... 8 more
```

https://github.com/Azure/azure-notificationhubs-android/blob/4dc585a982854bc7ab7ac8eab0ef9fc7ecec731e/notification-hubs-sdk/src/main/java/com/microsoft/windowsazure/messaging/notificationhubs/FirebaseReceiver.java#L29-L31

This creates a NotificationHub with a null PushChannelVisitor so when it tries to get the channel it crashes on create. I'm thinking the NotificationHub class needs a `IsInitalized` flag that gets set on `NotificationHub.Start` and that gets checked inside the `FirebaseReceiver` before every call to the notification hub.

Also our app does not call `NotifcationHub.Start` until after the user has logged in since our hub connection strings is api driven. I feel like the following code below only needs to be called after `NotificationHub.Start` is called, not with the firebase service is booted up.

https://github.com/Azure/azure-notificationhubs-android/blob/4dc585a982854bc7ab7ac8eab0ef9fc7ecec731e/notification-hubs-sdk/src/main/java/com/microsoft/windowsazure/messaging/notificationhubs/FirebaseReceiver.java#L50-L62

**Comment by marstr** [comment]
@acastr7, I'm going to pull this into a separate issue. Thanks for bringing this to our attention.
