### ISSUE TITLE
create service to keep checking if there a new push notification 

### ISSUE THREAD

**Issue by thegamer123** [Azure/azure-notificationhubs-android#137]
please how to create a  service to keep checking if there a new push notification using the new sdk implementation : 

i want NotificationListener to detect push notification when app is killed

**Comment by eric-labelle** [comment]
I'm confused about this one also. I tested with Azure Portal "Test Send" and never received the notification when the app is killed. Only if it is in foreground or background. 
If I go through FCM console directly though I do receive the notification on that same device registered through ANH.

**Comment by marstr** [comment]
Howdy folks,

`FirebaseReceiver` is a Service that will automatically be running in the background for you listening for notifications when you use the new namespace. There are some Android/Firebase limitations around when Android will actually deliver the notifications to your app (regardless of whether you're using our SDK or not.) You can read more about the details of delivery timing here: https://firebase.google.com/docs/cloud-messaging/android/receive

A key difference between the FCM console experience and our Test Send payload is whether or not the payload included will have a `"notification"` property. In the FCM console, it always will. At time of writing, our Test Send initially only includes a `"data"` property, but you can fully customize the payload.

**Comment by eric-labelle** [comment]
Yeah that's what I just noticed and pointed out in my other issue (  #139  ). Which reinforce the case about having more control over the payload fields. 👍

**Comment by aziztitu** [comment]
@eric-labelle As mentioned in the other issue (#139), there's a new SKU of the SDK available now that uses `RemoteMessage` directly.

Closing this issue since the users can now use the new SKU that allows them to access the "notification" property.

**Comment by aziztitu** [comment]
Closing this issue since the users can now use the new SKU that allows them to access the "notification" property.
