### ISSUE TITLE
How to register as a Baidu developer has changed

### ISSUE THREAD

**Issue by xingzhougmu** [Azure/azure-notificationhubs-android#16]
In this article on how to leverage Baidu notification service with Azure Notification Hub, the part on how to register as a Baidu developer is out of date. Could you please update this article?

You can refer to the following link to check what's the new process and portal to register as a Baidu developer.
http://developer.baidu.com/wiki/index.php?title=%E6%B3%A8%E5%86%8C%E6%88%90%E4%B8%BA%E5%BC%80%E5%8F%91%E8%80%85

Cheers,
Xing

**Comment by marstr** [comment]
Closing this issue out as stale.
