### ISSUE TITLE
How to Unregister azure Notification in Android

### ISSUE THREAD

**Issue by Maneesh528** [Azure/azure-notificationhubs-android#20]
Hi Team, I am using 
NotificationHub hub = new NotificationHub(NotificationSettings.HubName,
NotificationSettings.HubListenConnectionString, getActivity());
hub.unregister();

Still I am getting the Notifications in Android, Can any one help me to solve it...

**Comment by brannon** [comment]
Hi, thanks for the bug report! Would you be able to provide logs (from `adb logcat`) around the time you call `hub.unregister()`?

In the meantime, we'll try to reproduce the issue on our side.

**Comment by marstr** [comment]
Seems like this issue has gone stale. I'm going to close it out.
