### ISSUE TITLE
Notifications not being displayed

### ISSUE THREAD

**Issue by marklowe1** [Azure/azure-notificationhubs-android#21]
Hi,
I followed the tutorial here to create the fcm tutorial app but messages are not being displayed on my device after being successfully sent from the azure portal.

https://docs.microsoft.com/en-us/azure/notification-hubs/notification-hubs-android-push-notification-google-fcm-get-started

The following error is showing in logcat approx 1 second after I send a message from the portal:

```
04-02 14:44:03.561 9691-9691/com.microsoft.notificationhubs.fcmtutorialapp E/FirebaseInstanceId: Failed to resolve target intent service, skipping classname enforcement
04-02 14:44:03.562 1154-1830/? W/ActivityManager: Unable to start service Intent { act=com.google.firebase.MESSAGING_EVENT pkg=com.microsoft.notificationhubs.fcmtutorialapp (has extras) } U=0: not found
04-02 14:44:03.562 9691-9691/com.microsoft.notificationhubs.fcmtutorialapp E/FirebaseInstanceId: Error while delivering the message: ServiceIntent not found.
```

I then downloaded the sample code from the repo and added in my app keys and the same issue is happening.

**Comment by brannon** [comment]
Thanks for the report! We'll take a look and confirm with the sample.

**Comment by marstr** [comment]
Just finished walking through this tutorial, and I wasn't able to reproduce this issue. I'm going to close out this issue, assuming it's gone stale. If you're still running into trouble, @marklowe1 (or anybody else reading this) feel free to open a new issue.
