### ISSUE TITLE
Unregistering error handling - can't attempt to re-unregister if it has failed once

### ISSUE THREAD

**Issue by Brqqq** [Azure/azure-notificationhubs-android#34]
We want to unregister a template and handle the situation where this fails for connection related issues, for example when the notification hub servers aren't reachable.

The problem is that we can't do this correctly using the `unregisterTemplate` method on the NotificationHub instance.  When unregistering fails due to an internet connection, an exception is thrown that we can catch. But if we try to unregister again later, it won't actually do anything. So there is no API call made to Azure's servers to unregister.

My expectation is that unregistering makes an API call to Azure's servers and when that fails due to connection issues, I can just retry the same operation again later and it should make the API call.

The reason seems to be that once the API call is attempted, it will remove the registration from SharedPreferences even if the API call fails. The next time you attempt to unregister, it will check for this registration from SharedPreferences before attempting the API call. Because it's already removed, it won't find it there and then it will stop there without error, as if you're trying to unregister a template that never existed.

You can see the code that removes the registration regardless of the error [here](https://github.com/Azure/azure-notificationhubs-android/blob/master/src/notification-hubs-sdk/src/main/java/com/microsoft/windowsazure/messaging/NotificationHub.java#L482). `removeRegistrationId` is called regardless of the outcome of the API call it seems.

This is contrary to the iOS implementation, [that seems to specifically check](https://github.com/Azure/azure-notificationhubs-ios/blob/master/src/WindowsAzureMessaging/WindowsAzureMessaging/SBNotificationHub.m#L750) if the API call succeeded before removing the registration locally.

**Comment by marstr** [comment]
Howdy @Brqqq, thanks for filing this issue. Our teams has been alerted to it, and will be taking a look as soon as we can.

**Comment by marstr** [comment]
Howdy @Brqqq, the fix for this issue is now merged into master. Expect the next version of this SDK to include these changes. We're beginning to release now, so you shouldn't have to wait too long to get the fix.

**Comment by Brqqq** [comment]
Thank you!
