### ISSUE TITLE
android sdk register unauthorized exception

### ISSUE THREAD

**Issue by malisert** [Azure/azure-notificationhubs-android#4]
Hi,

Android sdk gets unauthorized response from notification rest api while registering client to notification hub, if phone language is Turkish. There is no problem when language is English.
After some invastigation and debug session, I figured out the cause of exception. In Connection.java there is a line;

url = URLEncoder.encode(url, UTF8_ENCODING).toLowerCase(Locale.getDefault());

In this line, if phone language is Turkish, toLowerCase method converts I (capital i) to ı (dotless i). But it should convert to i (dotted i). This problem can be fixed by correcting this line like this:

url = URLEncoder.encode(url, UTF8_ENCODING).toLowerCase(Locale.ENGLISH);

**Comment by pouyactm** [comment]
Is there any update on this?

**Comment by marstr** [comment]
Looks like this was fixed in #1:
https://github.com/Azure/azure-notificationhubs-android/blob/37082351049332d9d6e9eb03ba2ac3bbc1dea863/src/notification-hubs-sdk/src/main/java/com/microsoft/windowsazure/messaging/Connection.java#L313
